[package]
name = "rewriter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.speed]
inherits = "release"
opt-level = 3

[profile.release]
opt-level = "z"

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.69"
oxc_allocator = "0.20.0"
oxc_ast = { version = "0.20.0", features = ["serialize"]}
oxc_parser = { version = "0.20.0" }
oxc_span = "0.20.0"
oxc_syntax = "0.20.0"
serde = "1.0.204"
serde-wasm-bindgen = "0.6.5"
url = "2.5.2"
wasm-bindgen =  "0.2.92"
