[package]
name = "rewriter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.69"
oxc_allocator = "0.20.0"
oxc_ast = { version = "0.20.0", features = ["serialize"]}
oxc_parser = { version = "0.20.0" }
oxc_span = "0.20.0"
oxc_syntax = "0.20.0"
serde = "1.0.204"
serde-wasm-bindgen = "0.6.5"
url = "2.5.2"
urlencoding = "2.1.3"
wasm-bindgen =  "0.2.92"
