name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: install wbg
        run: cargo install wasm-bindgen-cli
      - name: Setup Binaryen
        uses: Aandreba/setup-binaryen@v1.0.0
        with:
          token: ${{ github.token }}

      - name: Install dependencies
        run: npm install

      - name: Build Rewriter
        run: npm run rewriter:build

      - name: Build Scramjet
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scramjet
          path: |
            dist/*.js
            dist/*.js.map

  upload:
    name: Upload release
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Delete old release and tag
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: latest
          github_token: ${{ github.token }}

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: scramjet
          path: build

      - name: Display structure of downloaded files
        run: ls -R

      - name: Zip files
        run: zip -r scramjet.zip build/

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: Continuous Build
          tag: latest
          commit: main
          body: ${{ github.event.head_commit.message }}
          artifacts: "scramjet.zip"
          prerelease: true
